// lib/articlesData.js

export const SEO_ARTICLES = [
  {
    slug: "sahne-kiralama-nedir",
    title: "Sahne Kiralama Nedir? Hangi Etkinliklerde Tercih Edilir?",
    desc: "Konser, lansman, bayi toplantısı gibi etkinliklerde sahne seçimi ve modüler sistemlerin avantajları.",
    image: "/img/articles/sahne-kiralama-1.webp",
    alt: "Konser etkinliğinde kurulu profesyonel sahne ve ışık sistemi",
    tag: "Sahne",
    read: "3-5 dk",
    datePublished: "2025-01-15",
  },
  {
    slug: "led-ekran-kiralama-rehberi",
    title: "LED Ekran Kiralama Rehberi: P2-P6 Farkı, Parlaklık ve Kurulum",
    desc: "Pixel pitch, nit değeri ve iç/dış mekân kullanımında dikkat edilecek teknik kriterler.",
    image: "/img/articles/led-ekran-1.webp",
    alt: "Büyük salonda P3 LED ekran kurulum örneği",
    tag: "LED Ekran",
    read: "4-6 dk",
    datePublished: "2025-02-03",
  },
  {
    slug: "ses-isik-sistemleri-secimi",
    title: "Ses-Işık Sistemlerinde Doğru Ekipman Seçimi: Line Array, DMX, Akustik",
    desc: "Alan akustiğine göre hoparlör yerleşimi, ışık senaryosu ve DMX kontrol ipuçları.",
    image: "/img/articles/ses-isik-1.webp",
    alt: "Sahne üzerinde robot ışık ve truss yapısı",
    tag: "Ses & Işık",
    read: "3-4 dk",
    datePublished: "2025-02-18",
  },
  {
    slug: "podyum-kiralama-olculer",
    title: "Podyum Kiralama Ölçüleri ve Malzeme Seçimi: 1×1 / 1×2 Paneller",
    desc: "Zemin düzeni, kaymaz kaplama ve güvenli yükseklikler için pratik kontrol listesi.",
    image: "/img/articles/podyum-1.webp",
    alt: "Etkinlik alanında modüler podyum kurulumu",
    tag: "Podyum",
    read: "2-3 dk",
    datePublished: "2025-03-04",
  },
  {
    slug: "dis-mekan-etkinliklerde-cadir",
    title: "Dış Mekân Etkinliklerinde Çadır Kiralama: Rüzgâr, Yağmur ve Zemin",
    desc: "Kare/çadır tipleri, güvenli ankraj ve su tahliye çözümlerine kısa bir giriş.",
    image: "/img/articles/cadir-1.webp",
    alt: "Açık alanda kurulu etkinlik çadırı",
    tag: "Çadır",
    read: "2-4 dk",
    datePublished: "2025-03-18",
  },
  {
    slug: "jenerator-guc-planlama",
    title: "Etkinliklerde Jeneratör Güç Planlama: LED Ekran ve Ses İçin Watt Hesabı",
    desc: "LED ekran, ses-ışık, iklimlendirme gibi tüketimlerin toplam güç hesabı örneği.",
    image: "/img/articles/jenerator-1.webp",
    alt: "Saha arkasında konumlandırılmış jeneratör",
    tag: "Güç",
    read: "3-5 dk",
    datePublished: "2025-04-05",
  },
];
